Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.define "hnaamaS" do |server|
    server.vm.hostname = "hnaamaS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |v|
      v.name   = "hnaamaS"
      v.cpus   = 1
      v.memory = 1024
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end

    server.vm.provision "shell", path: "scripts/setup.sh"
  end
end
