Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"

	config.vm.define "smounirS" do |smounirS|
		smounirS.vm.hostname = "smounirS"
		smounirS.vm.network "private_network", ip: "192.168.56.110"
		smounirS.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
		end
		smounirS.vm.provision "shell", path: "k3s-server.sh"
	end

	config.vm.define "smounirSW" do |smounirSW|
		smounirSW.vm.hostname = "smounirSW"
		smounirSW.vm.network "private_network", ip: "192.168.56.111"
		smounirSW.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
		end
		smounirSW.vm.provision "shell", path: "k3s-agent.sh"
	end

end
