Vagrant.configure("2") do |config|
	config.vm.box = "generic/ubuntu2004"

	config.vm.provision "shell", path: "kubectl.sh"

	config.vm.provider "libvirt" do |v|
		v.memory = 1024
		v.cpus = 2
	end
	
	config.vm.define "smounirS" do |smounirS|
		smounirS.vm.hostname = "smounirS"
		smounirS.vm.network "private_network", ip: "192.168.56.110"
		smounirS.vm.provision "shell", path: "k3s-server.sh"
	end

	config.vm.define "smounirSW" do |smounirSW|
		smounirSW.vm.hostname = "smounirSW"
		smounirSW.vm.network "private_network", ip: "192.168.56.111"
		smounirSW.vm.provision "shell", path: "k3s-agent.sh"
	end

end
